{
  "ID": "oval:org.debian:def:20095011",
  "Class": "vulnerability",
  "Metadata": {
    "Title": "CVE-2009-5011",
    "AffectedList": [
      {
        "Family": "unix",
        "Platform": "Debian GNU/Linux 10",
        "Product": "python-pyftpdlib"
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2009-5011",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-5011"
      }
    ],
    "Description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.",
    "Debian": {
      "MoreInfo": ""
    }
  },
  "Criteria": {
    "Operator": "AND",
    "Criterias": [
      {
        "Operator": "OR",
        "Criterias": [
          {
            "Operator": "AND",
            "Criterias": null,
            "Criterions": [
              {
                "Negate": false,
                "TestRef": "oval:org.debian.oval:tst:2",
                "Comment": "all architecture"
              },
              {
                "Negate": false,
                "TestRef": "oval:org.debian.oval:tst:3842",
                "Comment": "python-pyftpdlib DPKG is earlier than 0.5.2-1"
              }
            ]
          }
        ],
        "Criterions": null
      }
    ],
    "Criterions": [
      {
        "Negate": false,
        "TestRef": "oval:org.debian.oval:tst:1",
        "Comment": "Debian 10 is installed"
      }
    ]
  }
}