{
  "debianbug": 970099,
  "description": "In Lib/tarfile.py in Python through 3.8.3, an attacker is able to craft a TAR archive leading to an infinite loop when opened by tarfile.open, because _proc_pax lacks header validation.",
  "releases": {
    "sid": {
      "fixed_version": "3.8.5-1",
      "repositories": {
        "sid": "3.8.7-1"
      },
      "status": "resolved",
      "urgency": "low"
    }
  },
  "scope": "local"
}