{
  "description": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.",
  "releases": {
    "bullseye": {
      "repositories": {
        "bullseye": "1.10.0-1"
      },
      "status": "open",
      "urgency": "not yet assigned"
    },
    "buster": {
      "repositories": {
        "buster": "1.7.0-2"
      },
      "status": "open",
      "urgency": "not yet assigned"
    },
    "sid": {
      "repositories": {
        "sid": "1.10.0-1"
      },
      "status": "open",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "nodsa": "Minor issue",
      "nodsa_reason": "postponed",
      "repositories": {
        "stretch": "1.4.32-3"
      },
      "status": "open",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}