{
  "description": "An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node-\u003emn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
  "releases": {
    "bullseye": {
      "repositories": {
        "bullseye": "1.0.0-1"
      },
      "status": "open",
      "urgency": "unimportant"
    },
    "sid": {
      "repositories": {
        "sid": "1.0.0-1"
      },
      "status": "open",
      "urgency": "unimportant"
    },
    "stretch": {
      "repositories": {
        "stretch": "0.86-1"
      },
      "status": "open",
      "urgency": "unimportant"
    }
  },
  "scope": "local"
}