{
  "debianbug": 840958,
  "description": "The _dwarf_get_size_of_val function in libdwarf/dwarf_util.c in Libdwarf before 20161124 allows remote attackers to cause a denial of service (out-of-bounds read) by calling the dwarfdump command on a crafted file.",
  "releases": {
    "bullseye": {
      "fixed_version": "20161001-2",
      "repositories": {
        "bullseye": "20201201-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "20161001-2",
      "repositories": {
        "buster": "20180809-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "20161001-2",
      "repositories": {
        "sid": "20201201-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "20161001-2",
      "repositories": {
        "stretch": "20161124-1+deb9u1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}